# Generated by Django 4.1.3 on 2023-01-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_globales_id_alter_globales_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Globales',
        ),
    ]
