# Generated by Django 4.1.3 on 2023-01-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_globales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Globales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('valor', models.CharField(max_length=500)),
            ],
        ),
    ]
