# Generated by Django 4.1.3 on 2023-01-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_globales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globales',
            name='nombre',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
