# Generated by Django 4.1.3 on 2023-01-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_globales_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_corte_energia',
            field=models.DateField(null=True),
        ),
    ]
